baseURL = "https://forexsu.co"
defaultContentLanguage = "nl"
disqusShortname = ""
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
googleAnalytics = ""
hasCJKLanguage = true
languageCode = "nl"
paginate = 5
rssLimit = 10
theme = "texify"
timeZone = "America/Paramaribo"
title = "foreign exchange suriname"
[author]
email = "hello@forexsu.co"
name = "forexsu"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "emacs"
[params]
customCSS = ["/css/own.css"]
customJS = [""]
dateFormat = "2006.01.02"
description = "actuele wisselkoersen op één plek"
emphasisWithDots = true
favicon = "favicon.ico"
footnote = ""
fullTextRSS = true
keywords = ["foreign exchange suriname", "suriname", "forex suriname", "forex su", "forexsu", "fxs", "forexsu.co", "foreignexchangesuriname.com"]
since = "2022"
timeFormat = "15:04"
toc = false
[params.giscus]
enable = false
script = ""
[params.math]
enable = false
use = "katex"
[params.outdated]
enable = true
limit = 0
warning = "⚠️ oude koersen %d dagen oud."
[params.own]
fullTitle = "foreign exchange suriname"
[params.utterances]
enable = false
script = ""
[taxonomies]
