---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: data/dsb.json
  label: dsb
- type: document
  path: data/fina.json
  label: fina
- type: document
  path: data/hakrin.json
  label: hakrin
- type: document
  path: data/republic.json
  label: republic
- type: document
  path: data/cme.json
  label: cme
- type: document
  path: data/dallex.json
  label: dallex
- type: document
  path: data/florin.json
  label: florin
- type: document
  path: data/multi.json
  label: multi
- type: document
  path: data/dalflo.json
  label: dalflo
- type: document
  path: content/demo.md
  label: demo
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
